name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name 'sayedsafquat'
        git config --global user.email 'safquat615@gmail.com'
        git checkout -b gh-pages
        # Replace 'public' with the actual folder containing your HTML page if needed.
        git add .
        git commit -m 'Deploy to GitHub Pages'
        git push origin gh-pages
